### ISSUE TITLE
Error while trying to run samples

### ISSUE THREAD

**Issue by ashishGuliya** [flipkart-incubator/Poseidon#170]
I am trying to use Poseidon in one of my projects.
However no mater how much I try, i keep getting error, while trying to run it.

When i try to run "mvn clean install" I get :  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (generator) on project sampleSC: An exception occured while executing the Java class. null: InvocationTargetException: javax/annotation/Generated: javax.a
nnotation.Generated -> [Help 1]

I have checkout the code as is, and havn't made any changes to it.

**Comment by pmohankumar** [comment]
Can you specify your java version?
>> java -version

Most likely you are with Java 9/10/11, where this class is moved to a different package [javax.annotation.processing.Generated](https://docs.oracle.com/javase/9/docs/api/javax/annotation/processing/Generated.html) instead of [javax.annotation.Generated](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html). If so, please try building with JDK 1.8.
